apiVersion: projectriff.io/v1alpha1
kind: Function
metadata:
  name: vote-counter
spec:
  protocol: grpc
  input: votes
  output: counted-votes
  idleTimeoutMs: 5000
  container:
    image: projectriff/vote-counter:0.2.2
    env:
    - name: NODE_DEBUG
      value: riff
    - name: REDIS_HOST
      value: counters-redis-master
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: counters-redis
          key: redis-password
